name: Deploy the shadowsocks application to Google Cloud Run
on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Build Docker image
        run: |
          docker build . --tag ${{ secrets.GCLOUD_LOCATION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}/shadowsocks-image
          docker tag ${{ secrets.GCLOUD_LOCATION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}/shadowsocks-image ${{ secrets.GCLOUD_LOCATION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}/shadowsocks-image:google-tag
      
      - name: Authenticate into Google Cloud Platform
        uses: google-github-actions/auth@v0
        with:
          service_account: ${{ secrets.GCLOUD_EMAIL }}
          credentials_json: ${{ secrets.GCLOUD_AUTH }}

      - name: Configure Docker to use Google Cloud Platform
        run: "gcloud auth configure-docker ${{ secrets.GCLOUD_LOCATION }}-docker.pkg.dev --quiet"

      - name: Push image to Google Cloud Artifact Registry
        run: |
          docker push ${{ secrets.GCLOUD_LOCATION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}/shadowsocks-image:google-tag

      - name: Install beta commands
        run: |
          sudo apt-get remove google-cloud-sdk
          curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-399.0.0-linux-x86_64.tar.gz
          tar -xf google-cloud-cli-399.0.0-linux-x86_64.tar.gz
          ./google-cloud-sdk/install.sh
          ./google-cloud-sdk/bin/gcloud components install beta --quiet

      - name: Deploy on Cloud run
        run: |
          ./google-cloud-sdk/bin/gcloud beta run deploy ${{ secrets.GCLOUD_APP_NAME }} --quiet --image ${{ secrets.GCLOUD_LOCATION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}/shadowsocks-image:google-tag --project ${{ secrets.GCLOUD_PROJECT }} --region ${{ secrets.GCLOUD_LOCATION }} --platform managed